---
job: extension
config:
  # this name will be the folder and filename name
  name: "NAME_FLUX_PAseer"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "output"
      # uncomment to see performance stats in the terminal every N steps
#      performance_log_every: 1000
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
#      trigger_word: "p3r5on"
      network:
        type: "lora"
        linear: 8
        linear_alpha: 1
        network_kwargs:
          only_if_contains:
            - "transformer.transformer_blocks.0"
            - "transformer.transformer_blocks.1"
            - "transformer.transformer_blocks.2"
            - "transformer.transformer_blocks.10"
            - "transformer.transformer_blocks.14"
            - "transformer.transformer_blocks.16"
            - "transformer.transformer_blocks.17"
            - "transformer.transformer_blocks.18"
            - "transformer.single_transformer_blocks.0"
            - "transformer.single_transformer_blocks.1"
            - "transformer.single_transformer_blocks.4"
            - "transformer.single_transformer_blocks.6"
            - "transformer.single_transformer_blocks.7"
            - "transformer.single_transformer_blocks.8"
            - "transformer.single_transformer_blocks.9"
            - "transformer.single_transformer_blocks.10"
            - "transformer.single_transformer_blocks.11"
            - "transformer.single_transformer_blocks.12"
            - "transformer.single_transformer_blocks.13"
            - "transformer.single_transformer_blocks.15"
            - "transformer.single_transformer_blocks.19"
            - "transformer.single_transformer_blocks.20"
            - "transformer.single_transformer_blocks.23"
            - "transformer.single_transformer_blocks.25"
            - "transformer.single_transformer_blocks.27"
            - "transformer.single_transformer_blocks.29"
            - "transformer.single_transformer_blocks.30"
            - "transformer.single_transformer_blocks.33"
            - "transformer.single_transformer_blocks.34"
            - "transformer.single_transformer_blocks.35"
            - "transformer.single_transformer_blocks.36.proj_out"
            - "transformer.single_transformer_blocks.37"
      save:
        dtype: float16 # precision to save
        save_every: 300 # save every this many steps
        max_step_saves_to_keep: 3 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
        # You can either set up a HF_TOKEN env variable or you'll be prompted to log-in         
#       hf_repo_id: your-username/your-model-slug
#       hf_private: true #whether the repo is private or public
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "/root/ai-toolkit/训练集"
          caption_ext: "txt"
          caption_dropout_rate: 0  # will drop out the caption 5% of time
          shuffle_tokens: true  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 1024 ]  # flux enjoys multiple resolutions
          flip_aug: True
          keep_tokens: 2
          num_repeats: 2
      train:
        reg_weight: 0.6
        batch_size: 1
        steps: 2400  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation: 2
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        #train_clip: true
        #train_t5: false
        #t5_trainable_layers: [10, 11, 12]
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 6.8e-4
        lr_scheduler: "polynomial"  #constant
        lr_scheduler_params:
            power: 0.2
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "/root/ai-toolkit/FLUX.1-dev"
        is_flux: true
        quantize: true  # run 8bit mixed precision
#        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 300 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
#          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"\
          - "example, tag"
#          - "example, tags"
#          - "a horse is a DJ at a night club, fish eye lens, smoke machine, lazer lights, holding a martini"
#          - "a man showing off his cool new t shirt at the beach, a shark is jumping out of the water in the background"
#          - "a bear building a log cabin in the snow covered mountains"
#          - "woman playing the guitar, on stage, singing a song, laser lights, punk rocker"
#          - "hipster man with a beard, building a chair, in a wood shop"
#          - "photo of a man, white background, medium shot, modeling clothing, studio lighting, white backdrop"
#          - "a man holding a sign that says, 'this is a sign'"
#          - "a bulldog, in a post apocalyptic world, with a shotgun, in a leather jacket, in a desert, with a motorcycle"
        neg: ""  # not used on flux
        seed: 123456
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[PAseer]"
  version: '1.0'
